// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBLj4rZ6VMo6CPqigOTtaXwftw1VyxRmw',
    appId: '1:1070407595847:web:cbf49df075054e07dafe62',
    messagingSenderId: '1070407595847',
    projectId: 'uberclone-40fa9',
    authDomain: 'uberclone-40fa9.firebaseapp.com',
    databaseURL: 'https://uberclone-40fa9-default-rtdb.firebaseio.com',
    storageBucket: 'uberclone-40fa9.appspot.com',
    measurementId: 'G-MXHJB5SBSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv83GAp92S1NDiuRBMRTyvU74Sqtb24cc',
    appId: '1:1070407595847:android:960b54447e08e0c6dafe62',
    messagingSenderId: '1070407595847',
    projectId: 'uberclone-40fa9',
    databaseURL: 'https://uberclone-40fa9-default-rtdb.firebaseio.com',
    storageBucket: 'uberclone-40fa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpou2h5MBnJWUN98YMYuH7ZTgbKpRugrw',
    appId: '1:1070407595847:ios:7cffe8dcb4291098dafe62',
    messagingSenderId: '1070407595847',
    projectId: 'uberclone-40fa9',
    databaseURL: 'https://uberclone-40fa9-default-rtdb.firebaseio.com',
    storageBucket: 'uberclone-40fa9.appspot.com',
    iosBundleId: 'com.example.driversApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpou2h5MBnJWUN98YMYuH7ZTgbKpRugrw',
    appId: '1:1070407595847:ios:3ed3468b1e30db29dafe62',
    messagingSenderId: '1070407595847',
    projectId: 'uberclone-40fa9',
    databaseURL: 'https://uberclone-40fa9-default-rtdb.firebaseio.com',
    storageBucket: 'uberclone-40fa9.appspot.com',
    iosBundleId: 'com.example.driversApp.RunnerTests',
  );
}
